### ISSUE TITLE
View are not updating on locale change if strings are provided using data binding

### ISSUE THREAD

**Issue by ashu5398** [B3nedikt/reword#11]
If I have set a string from strings.xml to a textview using databinding library, then on a locale change strings are not getting updated without a recreate of activity. Can I get any help on this?

**Comment by B3nedikt** [comment]
Sure. Assuming you use both databinding and set strings resources directly in XML, you need something like this:

```
            Reword.reword(window
                    .decorView
                    .findViewById<ContentFrameLayout>(android.R.id.content))

            binding.invalidateAll()
```

"this" is your root activity here, "binding" is the databinding used at your root activity. Hope this helps :)

**Comment by ashu5398** [comment]
That worked !! Thanks for help

**Comment by B3nedikt** [comment]
You're welcome :)
