### ISSUE TITLE
Unable to use the actual ViewTransformer, it's always using the parent one

### ISSUE THREAD

**Issue by Vittt2008** [B3nedikt/reword#25]
## Description
`ViewTransformerManager` has predefined `ViewTransformers`, so based on the code viewTransformer.viewType.isInstance(view), it finds always the first viewTransformers, so it means that the order is important.

For instance, we have `CustomEditText` with `CustomEditTextViewTransformer`, and due to the fact that `EditText` inherits classic Android `TextView`, `ViewTransformerManager` always return `TextViewViewTransformer`, but not the specific one `CustomEditTextViewTransformer`

## Suggestion
- During the search, try to find the most specific and then call `isInstance()`

## Link To PR
Created PR: https://github.com/B3nedikt/reword/pull/24

**Comment by B3nedikt** [comment]
I merged your PR, thanks for your contribution :)
Released with version 4.0.2
