### ISSUE TITLE
Getting duplicate Kotlin classes during Android Studio build for word 'dev.b3nedikt.reword:reword:4.0.3'

### ISSUE THREAD

**Issue by adanecito** [B3nedikt/reword#33]
Just recently upgraded from 4.0.2 to 4.0.3 for reword saying duplicate kotlin classes found. I am using gradle plugin 7.4.0 and gradle 7.5

Using latest stable android studio release.

Duplicate class kotlin.random.jdk8.PlatformThreadLocalRandom found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.6.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20)
Duplicate class kotlin.streams.jdk8.StreamsKt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.6.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20)
Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$1 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.6.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20)
Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$2 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.6.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20)
Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$3 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.6.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20)
Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$4 found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.6.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20)
Duplicate class kotlin.text.jdk8.RegexExtensionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.6.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20)
Duplicate class kotlin.time.jdk8.DurationConversionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.6.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20)

**Comment by B3nedikt** [comment]
@adanecito Should be fixed with 4.0.4 ;)
